Repository mattermost/mattermost-plugin-demo, pull requests merged in 2019-12, with the labels that each got.

#78 MM-20749: restrict post menu nesting
  webapp/src/plugin.jsx
Labels: 3: Reviews Complete

#76 [MM-19970] Add example usage of EnsureBot to the Demo Plugin
  go.mod
  go.sum
  server/configuration.go
  server/configuration_test.go
Labels: 3: Reviews Complete

#80 Release v0.4.0
  plugin.json
  server/manifest.go
  webapp/src/manifest.js
Labels: 2: Dev Review, 3: Reviews Complete

#79 npm audit fix --save
  webapp/package-lock.json
Labels: Tests/Not Needed

#77 MM-19902 - Added example of channel header dropdown menu item
  plugin.json
  webapp/README.md
  webapp/docs/channel_header_dropdown.png
  webapp/src/actions.js
  webapp/src/plugin.jsx
Labels: 3: Reviews Complete, QA Review Done

#81 Bump Mattermost to 5.18
  build/manifest/main.go
  go.mod
  go.sum
  server/activate_hooks_test.go
  server/channel_hooks.go
  server/command_hooks.go
  server/configuration.go
  server/configuration_test.go
  server/file_hooks.go
  server/http_hooks.go
  server/login_hooks.go
  server/main.go
  server/message_hooks.go
  server/plugin.go
  server/plugin_message.go
  server/team_hooks.go
  server/user_hooks.go
Labels: 3: Reviews Complete, Tests/Not Needed
