Repository mattermost/mattermost-plugin-demo, pull requests merged in 2020-03, with the labels that each got.

#88 MM-17912 - slash command to exercise FileInfo search API
  go.mod
  plugin.json
  server/README.md
  server/command_hooks.go
Labels: 3: Reviews Complete, QA Review Done

#92 Drop deploy-release job
  .circleci/config.yml
Labels: 3: Reviews Complete

#85 MM-21984: introduce background job
  go.mod
  go.sum
  server/activate_hooks.go
  server/activate_hooks_test.go
  server/job.go
  server/plugin.go
Labels: QA Review Done

#90 MM-21987: Demonstrate resolution of mentions
  go.sum
  server/README.md
  server/command_hooks.go
Labels: 3: Reviews Complete, QA Review Done
