Repository mattermost/mattermost-plugin-demo, pull requests merged in 2021-01, with the labels that each got.

#136 import test setup files from webapp repo
  webapp/e2e/cypress.json
  webapp/e2e/cypress/fixtures/users.ts
  webapp/e2e/cypress/integration/crash_spec.ts
  webapp/e2e/cypress/plugins/index.ts
  webapp/e2e/cypress/support/api/common.d.ts
  webapp/e2e/cypress/support/api/common.ts
  webapp/e2e/cypress/support/api/index.ts
  webapp/e2e/cypress/support/api/plugin.d.ts
  webapp/e2e/cypress/support/api/plugin.ts
  webapp/e2e/cypress/support/constants.ts
  webapp/e2e/cypress/support/index.ts
  webapp/e2e/cypress/support/server_api_commands.ts
  webapp/e2e/cypress/support/ui_commands.ts
  webapp/e2e/package-lock.json
  webapp/e2e/package.json
Labels: 2: Dev Review

#137 [MM-30352] Automate backlogs - Plugins > Demo plugin functionality pt. 2 (2 test cases)
  webapp/e2e/cypress/integration/demo_channel_spec.js
  webapp/e2e/cypress/integration/enable_disable_hooks_spec.js
Labels: 4: Reviews Complete, AutoMerge

#138 Update plugin.json
  plugin.json
Labels: 4: Reviews Complete

#139 Update plugin.json
  plugin.json
Labels: 4: Reviews Complete
